default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: project_app_development

test:
  <<: *default
  database: project_app_test

